# 문제 1:
1. floorplans를 저장할 때 방:시드번호로 구성된 seed_cell_list  딕셔너리를 키로 해서 전체 floorplans를 저장한다. 
2. 이 때 `self.floorplans_dict[self.seed_cell_list] = self.floorplans` 이런 식으로 하면 seed_cell_list가 dictionary라서 hashable 하지 않다.  에러 발생
# 대안 1:
  튜플로 구조 변겅
    `self.floorplans_dict[tuple(self.seed_cell_list.items())] = self.floorplans`
# 구조적 문제 
### 1. 딕셔너리의 키로 사용하는 데이터의 크기
튜플 변환: self.seed_cell_list를 튜플로 변환하여 키로 사용하는 경우, 이 튜플의 크기가 크다면 메모리 사용량이 증가할 수 있습니다. 특히, 수만 개의 데이터를 저장하는 경우, 각 키가 차지하는 메모리 공간이 상당할 수 있습니다.
해시 충돌: 해시를 사용하면 키를 비교할 때 효율적이지만, 해시 충돌이 발생할 가능성도 있습니다. 충돌이 빈번하게 발생하면 딕셔너리의 검색 성능이 저하될 수 있습니다.
### 2. 키의 고유성 및 데이터 검색 효율성
고유성: self.seed_cell_list의 값이 고유한지 확인해야 합니다. 만약 동일한 값을 가진 키가 많다면 데이터 저장 시 의도하지 않은 덮어쓰기(overwriting)가 발생할 수 있습니다.
검색 효율성: 딕셔너리는 평균적으로 O(1)의 시간 복잡도로 검색이 가능하지만, 키가 커지거나 해시 충돌이 잦아질 경우, 실제 성능은 저하될 수 있습니다.
### 3. 메모리 사용량
메모리 최적화: 수만 개의 데이터가 저장될 경우, 메모리 사용량이 급격히 증가할 수 있습니다. 특히, 키의 크기가 크거나 복잡할 경우 메모리 사용량이 비효율적일 수 있습니다.
대안적 데이터 구조: 대규모 데이터셋의 경우, 데이터베이스나 다른 종류의 효율적인 데이터 구조(예: defaultdict 또는 OrderedDict)를 사용하는 것이 더 나을 수 있습니다.
### 4. 데이터의 지속성 및 관리
영구 저장: 수만 개의 데이터를 장시간 저장하고 관리해야 한다면, 메모리에만 의존하지 않고 파일 시스템이나 데이터베이스에 저장하는 방법을 고려해야 합니다.
데이터 관리: 메모리 내에서 수만 개의 항목을 관리하는 것은 복잡할 수 있으며, 데이터의 무결성을 유지하기 위한 추가적인 관리가 필요할 수 있습니다.
### 5. 대안 제안
데이터베이스 사용: 만약 데이터가 수만 개 이상으로 커지며 지속적인 검색 및 업데이트가 필요한 경우, SQLite나 NoSQL과 같은 경량 데이터베이스를 사용하는 것이 더 적절할 수 있습니다. 이를 통해 메모리 사용을 최적화하고, 더 큰 규모의 데이터를 효율적으로 관리할 수 있습니다.
고유 식별자를 단순화: 가능하다면 self.seed_cell_list와 같은 복잡한 구조 대신, 해시 값이나 간단한 고유 식별자(ID)를 사용하여 딕셔너리의 키로 사용하는 방법도 고려할 수 있습니다. 이렇게 하면 메모리 사용량이 줄어들고, 검색 속도도 향상될 수 있습니다.
 
# 고유 식별자를 단순화: 
- `self.seed_cell_list`와 같은 복잡한 구조 대신, 해시 값이나 간단한 고유 식별자(ID)를 사용하여 딕셔너리의 키로 사용하는 방법도 고려할 수 있습니다. 
- 이렇게 하면 메모리 사용량이 줄어들고, 검색 속도도 향상될 수 있습니다.

### 1. **고유 식별자(ID) 생성 방법 **

- `self.seed_cell_list`는 방번호와 방 배치의 시작점을 가진 딕셔너리. 
- 해시 값을 사용한 고유 식별자 생성
- 예시: `hashlib` 라이브러리를 사용하여 SHA-256 해시 생성. 이 해시 값은 `self.seed_cell_list`의 문자열 표현을 기반으로 하며, 매우 고유한 식별자 역할을 합


In [1]:
import hashlib

def generate_unique_id(seed_cell_list):
    # seed_cell_list를 문자열로 변환한 후, 해시 값을 생성
    seed_str = str(seed_cell_list)
    unique_id = hashlib.sha256(seed_str.encode('utf-8')).hexdigest()
    return unique_id


### 2. **딕셔너리에 고유 식별자(ID) 사용**

생성된 고유 식별자(ID)를 딕셔너리의 키로 사용하여 데이터를 저장


In [2]:
# 1. 고유 식별자 생성
unique_id = generate_unique_id(self.seed_cell_list)

# 2. 딕셔너리에 고유 식별자(ID) 사용하여 데이터 저장
self.floorplans_dict[unique_id] = self.floorplans


NameError: name 'self' is not defined

### 3. **고유 식별자 사용 예시**

수정된 `run_iteration()` 함수의 예시입니다.


In [ ]:
import hashlib

def generate_unique_id(seed_cell_list):
    seed_str = str(seed_cell_list)
    unique_id = hashlib.sha256(seed_str.encode('utf-8')).hexdigest()
    return unique_id

def run_iteration(self):
    if self.iteration < 10:
        self.ok_button.config(state=tk.DISABLED)

        initial_floorplan = create_floorplan(self.seed, k=self.num_rooms, options=self.options)
        self.draw_floorplan(initial_floorplan, self.initial_canvas)
        simplified_floorplan, fit = self.get_optimal_from_initial_floorplan(initial_floorplan)
        self.draw_floorplan(simplified_floorplan, self.final_canvas)

        # 결과 저장
        self.floorplans.append((simplified_floorplan, fit))

        # OK 버튼 활성화
        self.ok_button.config(state=tk.NORMAL)

    else:
        self.fitness_label.config(text="Batch processing complete.")
        self.ok_button.config(state=tk.DISABLED)
        
        # 1. 고유 식별자 생성
        unique_id = generate_unique_id(self.seed_cell_list)
        
        # 2. 고유 식별자를 사용해 결과 저장
        self.floorplans_dict[unique_id] = self.floorplans


### 4. **고유 식별자 검색 및 사용**

나중에 `self.floorplans_dict`에서 데이터를 검색할 때도 동일한 방식으로 고유 식별자를 생성하여 사용.

In [ ]:

unique_id = generate_unique_id(some_seed_cell_list)
if unique_id in self.floorplans_dict:
    floorplans = self.floorplans_dict[unique_id]



### 결론

이 방법을 사용하면 `self.seed_cell_list`와 같은 복잡한 구조를 직접 딕셔너리의 키로 사용하는 대신, 고유 식별자(ID) 또는 해시 값을 사용하여 키를 단순화할 수 있습니다. 이렇게 하면 메모리 사용량이 줄어들고, 딕셔너리 검색 속도가 향상됩니다.

In [85]:
import numpy as np
import random

def find_parallel_adjacent_cells(floorplan, room_id):
    """
    주어진 방 번호에 대해 수평 또는 수직 방향으로 일직선상에 있는 셀들의 좌표를 찾고, 
    이 셀들이 다른 방과 인접해 있는지 확인하여 결과를 반환한다.
    
    Parameters:
    - floorplan: 2D numpy array, 플로어플랜의 배열 (각 셀은 방 번호를 가짐)
    - room_id: int, 찾고자 하는 방의 번호
    
    Returns:
    - result: list of tuples, 각 튜플은 (셀 좌표 리스트, 방향)으로 구성
    """
    result = []
    rows, cols = floorplan.shape

    # 수평 방향으로 일직선상에 있는 셀들 확인
    for i in range(rows):
        row_coords = [(i, j) for j in range(cols) if floorplan[i, j] == room_id]  # 수평 방향으로 일직선상에 있는 셀들
        if len(row_coords) >= 2:
            # 이 셀들이 상하 방향으로 다른 방과 인접해 있는지 확인
            for x, y in row_coords:
                if x > 0 and floorplan[x - 1, y] != room_id and floorplan[x - 1, y] != 0:
                    result.append((row_coords, 'up'))
                    break  # 중복 추가 방지
                if x < rows - 1 and floorplan[x + 1, y] != room_id and floorplan[x + 1, y] != 0:
                    result.append((row_coords, 'down'))
                    break  # 중복 추가 방지

    # 수직 방향으로 일직선상에 있는 셀들 확인
    for j in range(cols):
        col_coords = [(i, j) for i in range(rows) if floorplan[i, j] == room_id]  # 수직 방향으로 일직선상에 있는 셀들
        if len(col_coords) >= 2:
            # 이 셀들이 좌우 방향으로 다른 방과 인접해 있는지 확인
            for x, y in col_coords:
                if y > 0 and floorplan[x, y - 1] != room_id and floorplan[x, y - 1] != 0:
                    result.append((col_coords, 'left'))
                    break  # 중복 추가 방지
                if y < cols - 1 and floorplan[x, y + 1] != room_id and floorplan[x, y + 1] != 0:
                    result.append((col_coords, 'right'))
                    break  # 중복 추가 방지

    return result

def assign_cells_to_adjacent_room(floorplan, room_id):
    """
    주어진 방의 셀들을 인접한 다른 방의 번호로 할당한다.
    이때, 인접한 다른 방이 있는 방향 중 한 방향만 임의로 선택하여 할당한다.
    
    Parameters:
    - floorplan: 2D numpy array, 플로어플랜의 배열 (각 셀은 방 번호를 가짐)
    - room_id: int, 할당할 셀들의 방 번호
    
    Returns:
    - modified_floorplan: 할당된 후의 플로어플랜 배열
    """
    adjacent_cells = find_parallel_adjacent_cells(floorplan, room_id)
    
    if adjacent_cells:
        # 인접 방향 중 하나를 임의로 선택
        cells, direction = random.choice(adjacent_cells)
        
        for (x, y) in cells:
            if direction == 'up' and x > 0 and floorplan[x - 1, y] != 0:
                floorplan[x, y] = floorplan[x - 1, y]
            elif direction == 'down' and x < floorplan.shape[0] - 1 and floorplan[x + 1, y] != 0:
                floorplan[x, y] = floorplan[x + 1, y]
            elif direction == 'left' and y > 0 and floorplan[x, y - 1] != 0:
                floorplan[x, y] = floorplan[x, y - 1]
            elif direction == 'right' and y < floorplan.shape[1] - 1 and floorplan[x, y + 1] != 0:
                floorplan[x, y] = floorplan[x, y + 1]
    
    return floorplan


In [87]:
# 예제 플로어플랜
floorplan = np.array([
    [1, 1, 0, 2, 2],
    [1, 1, 0, 2, 2],
    [1, 1, 3, 3, 3],
    [4, 4, 3, 3, 3],
    [4, 4, 3, 5, 5]
])

print("원래 플로어플랜:")
print(floorplan)

# 방 3을 다른 방으로 할당
modified_floorplan = assign_cells_to_adjacent_room(floorplan, 3)

print("\n할당된 후의 플로어플랜:")
print(modified_floorplan)


원래 플로어플랜:
[[1 1 0 2 2]
 [1 1 0 2 2]
 [1 1 3 3 3]
 [4 4 3 3 3]
 [4 4 3 5 5]]

할당된 후의 플로어플랜:
[[1 1 0 2 2]
 [1 1 0 2 2]
 [1 1 1 3 3]
 [4 4 4 3 3]
 [4 4 4 5 5]]


In [92]:
import numpy as np
import random

def crossover(floorplan1, floorplan2):
    """
    두 플로어플랜을 교차하여 자식 플로어플랜을 생성한다.
    
    Parameters:
    - floorplan1: 2D numpy array, 첫 번째 부모 플로어플랜
    - floorplan2: 2D numpy array, 두 번째 부모 플로어플랜
    
    Returns:
    - child_floorplan: 2D numpy array, 생성된 자식 플로어플랜
    """
    rows, cols = floorplan1.shape
    child_floorplan = np.zeros((rows, cols), dtype=int)

    # 교차점을 임의로 선택 (예: 사분면)
    split_row = random.randint(1, rows - 2)
    split_col = random.randint(1, cols - 2)

    # 사분면을 기준으로 교차
    child_floorplan[:split_row, :split_col] = floorplan1[:split_row, :split_col]
    child_floorplan[split_row:, split_col:] = floorplan2[split_row:, split_col:]

    # 남은 부분 처리
    child_floorplan[:split_row, split_col:] = floorplan1[:split_row, split_col:]
    child_floorplan[split_row:, :split_col] = floorplan2[split_row:, :split_col]

    # 교차 후 방이 분리된 경우에 대한 처리 (옵션)
    # 방의 연결성을 보장하기 위해 추가적인 처리 로직이 필요할 수 있음

    return child_floorplan

def mutate(self, floorplan, mutation_rate):
    room_id = random.choice(range(8)) + 1
    if random.random() < mutation_rate:
        mutated_floorplan = assign_cells_to_adjacent_room(floorplan, room_id)
        return mutated_floorplan
    return floorplan


In [95]:
import numpy as np
import random

def crossover(floorplan1, floorplan2):
    """
    두 플로어플랜을 교차하여 자식 플로어플랜을 생성한다.
    
    Parameters:
    - floorplan1: 2D numpy array, 첫 번째 부모 플로어플랜
    - floorplan2: 2D numpy array, 두 번째 부모 플로어플랜
    
    Returns:
    - child_floorplan: 2D numpy array, 생성된 자식 플로어플랜
    """
    rows, cols = floorplan1.shape
    child_floorplan = np.zeros((rows, cols), dtype=int)

    # 교차점을 임의로 선택 (예: 사분면)
    split_row = random.randint(1, rows - 2)
    split_col = random.randint(1, cols - 2)

    # 사분면을 기준으로 교차
    child_floorplan[:split_row, :split_col] = floorplan1[:split_row, :split_col]
    child_floorplan[split_row:, split_col:] = floorplan2[split_row:, split_col:]

    # 남은 부분 처리
    child_floorplan[:split_row, split_col:] = floorplan1[:split_row, split_col:]
    child_floorplan[split_row:, :split_col] = floorplan2[split_row:, :split_col]

    return child_floorplan

def assign_cells_to_adjacent_room(floorplan, room_id):
    """
    주어진 방의 셀들을 인접한 다른 방의 번호로 할당한다.
    이때, 인접한 다른 방이 있는 방향 중 한 방향만 임의로 선택하여 할당한다.
    
    Parameters:
    - floorplan: 2D numpy array, 플로어플랜의 배열 (각 셀은 방 번호를 가짐)
    - room_id: int, 할당할 셀들의 방 번호
    
    Returns:
    - modified_floorplan: 할당된 후의 플로어플랜 배열
    """
    adjacent_cells = find_parallel_adjacent_cells(floorplan, room_id)
    
    if adjacent_cells:
        # 인접 방향 중 하나를 임의로 선택
        cells, direction = random.choice(adjacent_cells)
        
        for (x, y) in cells:
            if direction == 'up' and x > 0 and floorplan[x - 1, y] != 0:
                floorplan[x, y] = floorplan[x - 1, y]
            elif direction == 'down' and x < floorplan.shape[0] - 1 and floorplan[x + 1, y] != 0:
                floorplan[x, y] = floorplan[x + 1, y]
            elif direction == 'left' and y > 0 and floorplan[x, y - 1] != 0:
                floorplan[x, y] = floorplan[x, y - 1]
            elif direction == 'right' and y < floorplan.shape[1] - 1 and floorplan[x, y + 1] != 0:
                floorplan[x, y] = floorplan[x, y + 1]
    
    return floorplan

def mutate(floorplan, mutation_rate, num_rooms):
    room_id = random.choice(range(1, num_rooms + 1))
    if random.random() < mutation_rate:
        mutated_floorplan = assign_cells_to_adjacent_room(floorplan, room_id)
        return mutated_floorplan
    return floorplan

# 테스트 예제
if __name__ == "__main__":
    # 두 개의 부모 플로어플랜 정의 (방 번호가 동일해야 함)
    floorplan1 = np.array([
        [1, 1, 0, 2, 2],
        [1, 1, 0, 2, 2],
        [1, 1, 3, 3, 3],
        [4, 4, 3, 3, 3],
        [4, 4, 3, 5, 5]
    ])

    floorplan2 = np.array([
        [2, 2, 0, 1, 1],
        [4, 4, 0, 1, 1],
        [4, 4, 3, 3, 3],
        [4, 4, 3, 3, 3],
        [4, 4, 3, 5, 5]
    ])

    print("부모 플로어플랜 1:")
    print(floorplan1)
    print("\n부모 플로어플랜 2:")
    print(floorplan2)

    # 교차 수행
    child_floorplan = crossover(floorplan1, floorplan2)
    print("\n자식 플로어플랜 (교차 후):")
    print(child_floorplan)

    # 돌연변이 수행
    mutation_rate = 0.5
    num_rooms = 5  # 방의 총 개수
    mutated_floorplan = mutate(child_floorplan, mutation_rate, num_rooms)
    print("\n돌연변이 후 플로어플랜:")
    print(mutated_floorplan)


부모 플로어플랜 1:
[[1 1 0 2 2]
 [1 1 0 2 2]
 [1 1 3 3 3]
 [4 4 3 3 3]
 [4 4 3 5 5]]

부모 플로어플랜 2:
[[2 2 0 1 1]
 [4 4 0 1 1]
 [4 4 3 3 3]
 [4 4 3 3 3]
 [4 4 3 5 5]]

자식 플로어플랜 (교차 후):
[[1 1 0 2 2]
 [1 1 0 2 2]
 [1 1 3 3 3]
 [4 4 3 3 3]
 [4 4 3 5 5]]

돌연변이 후 플로어플랜:
[[1 1 0 2 2]
 [1 1 0 2 2]
 [1 1 3 3 3]
 [4 4 3 3 3]
 [4 4 3 5 5]]
